### PR TITLE
Remove loading of ppolicy schema

### PR DESCRIPTION
**Pull request by mabezi**
According to the [OpenLDAP documentation](https://www.openldap.org/doc/admin25/appendix-upgrading.html), the password policy is now hard-coded and automatically included. Therefore remove the files.

I don't have an overview of whether this has any implications. Therefore as a pull request for now.

### CODE REVIEW

**Comment by lukasjuhrich** [comment]
Did you verify that the integrated ppolicy module works and is loaded? because in the pycroft CI (for the stub LDAP docker container) I had a similar problem while trying to upgrade to bookworm, however just deleting the vendored ppolicy module/scheme and using the builtin module would somehow not work.

**Comment by mabezi** [comment]
Good point.
The first task obviously fails because the scheme is already built-in.
The third task `Configure ppolicy overlay` results in `overlay_config(): overlay "ppolicy" already in list`

I can check the Module load task only to a limited extent to see whether it is still necessary, as the module is already loaded.
```
09:50:00 mabezi@ldap1 ~ % sudo slapcat -n 0 | grep olcModuleLoad
syncrepl rid=001 searchbase="dc=agdsn,dc=me": no retry defined, using default
olcModuleLoad: {0}back_mdb
olcModuleLoad: {1}ppolicy
olcModuleLoad: {2}memberof
```

But it won't hurt to keep the task.

**Comment by Paktosan** [comment]
I have removed myself as reviewer as I don't know how OpenLDAP works.

**Comment by mabezi** [comment]
> In OpenLDAP 2.4 the slapo-ppolicy(5) overlay relied on a separate schema file to be included for it to function. This schema is now implemented internally in the slapo-ppolicy module. When upgrading slapd.conf(5) deployments the include statement for the schema must be removed. For slapd-config(5) deployments, the config database must be exported via slapcat and the old ppolicy schema removed from the export. The resulting config database can then be imported.

https://www.openldap.org/doc/admin25/appendix-upgrading.html

So it should be enough to just remove the schema.

**Comment by lukasjuhrich** [comment]
@mabezi as per my last comment, have you verified that the password policy works without the module? At that point I also knew that _in theory_ it should neither be required nor used, but in practice some stuff broke. I mean you can and probably should deploy this, but testing the functionality is definitely necessary.

Edit: By functionality testing i mean set a `pwdMinLength` of 2 and test that you cannot change some password to a 2 char password.

**Pull request merged**
